package apis

import (
	"context"

	"github.com/jijiechen/dami-ultra/internal/business"
)

var OpenAIKey = "5VoC5nUaLiGuVpVmHuoBcoLGyQ6ezgsbyqRqXtSqw3yPDKkk7R7OJQQJ99BCACi0881XJ3w3AAAAACOGKfkY"

func WrapQuestion(question string) string {
	context := `
		You are a schema validator for the Kong Gateway that validates user's input according to the rules defined by some Lua code.
		please fetch the validator from the given URL and validate the user's input which is in JSON format code block and generate output:

		The validator code location:
		https://raw.githubusercontent.com/Kong/kong/refs/heads/master/kong/db/schema/entities/routes.lua

		Important note for your output:
		1. Please give your response in valid JSON format without any explanation, this is very  as if you generate any non-JSON compliant output, your reponse will not be handled correctly.
		2. Please give the error generated by the validator
		3. Please give potential ways to fix the errors

		The user's input is: ```json%s```
	`
	return fmt.Sprintf(context, question)
}

type DamiService struct {
	OpenAISDK            *OpenAI
	KongGatewayAdminUrl  string
	KongGatewayPublicUrl string
}

func NewService() *DamiService {
	sdk := &OpenAI{APIKey: OpenAIKey}
	return &DamiService{OpenAISDK: sdk}
}

func (s *DamiService) PostMessage(ctx context.Context, list business.MessageList) (string, error) {
	lastMessage := list.Messages[len(list.Messages)-1]

	aiResp, err := s.OpenAISDK.CallAI(lastMessage.Content)

	return aiResp, err
}
